### ISSUE TITLE
Can I use this for citra? If so, how?

### ISSUE THREAD

**Issue by ghost** [mid-kid/CakesForeveryWan#10]
I have been trying to run roms on citra for a few months now and cannot seem to get roms and homebrew to work.

**Comment by Syphurith** [comment]
@Jkhemili Sorry this is a CFW and you can only use this to run your backups with 3ds console. Citra needs decrypted CCI to work, thus you should get your backups and use d0k3/decrypt9 to decrypt the content (Game Decryptor, NCCH/CXI).. You should checkout citra wiki or search for tutorials first. BTW, citra do no support illegal rom/backups and please not spoil the issue tracker of citra or this.

**Comment by mid-kid** [comment]
This software modifies some parts of the 3ds' memory to be able to bypass singature checks (among others). Citra as a whole works way differently. It just emulates the parts that are essential for loading games, nothing more. There's been instances of commertial games running smoothly on it, but a CFW won't help you with that.
