### ISSUE TITLE
Does not compile in Windows....

### ISSUE THREAD

**Issue by ApacheThunder** [mid-kid/CakesForeveryWan#20]
Seems to be armips related. What build of armips does it need now? I try to compile it and get this:

patches.s(51) error: Invalid expression
patches.s(53) error: Invalid expression
patches.s(51) error: Invalid expression
patches.s(53) error: Invalid expression
patches.s(51) error: No if clause active
patches.s(51) error: No if clause active
patches.s(52) warning: Opcode not word aligned
patches.s(53) error: No if clause active
patches.s(53) error: No if clause active
Aborting.
Couldn't compile version 0x50 for some reason.
make: **\* [build/patches/reboot.baked] Error 1

I've tried a build by d0k3 and the original build from devkitpro release 45. But still no go. It won't compile after the latest commit....

**Comment by mariogamer2** [comment]
me it's work with latest armips and devkit ARM 45

linux ubuntu 15.10

**Comment by ApacheThunder** [comment]
Does someone have a compiled version of armips? I found a gibhub page but it's cmake. I can't really compile cmake stuff right now. I'm using Windows 7 right now. Maybe there isn't a build for WIndows yet....

**Comment by mariogamer2** [comment]
wait a sec...

https://cmake.org/download/

**Comment by ApacheThunder** [comment]
I have cmake. The problem is I'm not familiar with the command line switches it needs to compile things and I've only managed to compile TWLSaveTool with it thus far.

**Comment by mariogamer2** [comment]
run this: cmake /path/to/armips

than,go to armips directory and run: make

and then,put armips.exe in a directory who is in your path

**Comment by ApacheThunder** [comment]
It won't compile:

---

CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

```
cl
```

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

## Configuring incomplete, errors occurred!

I'm not hunting down any more dependencies for this. cmake is a nightmare to deal with. I'm not going to attempt to compile anymore cmake crap anytime soon.

**Comment by mariogamer2** [comment]
Don't know what is the "compiler",sorry.

For me,it is probably GCC (gnu across compiler) on linux.

**Comment by Syphurith** [comment]
@ApacheThunder `CMake` command line edition would always try to use `Visual Studio` toolchain if any, but no fallback for this. To solve this you had to set the MakeFile Type for it to be `MINGW` or `MSYS` as its parameter. Or else you can use its GUI version. BTW this could be just the design fault in CMake.

**Comment by ApacheThunder** [comment]
I've tried MinGW/MSYS build settings with the GUI version. It fails to compile it. :(

**Comment by ApacheThunder** [comment]
I've given up trying to fix compiling armips. Instead I just reverted this commit:

https://github.com/mid-kid/CakesForeveryWan/commit/5988f10951d4d6e006836339195c5f6db444fa72

Back to what it was before. It compiles now. Hopefully this doesn't cause problems, because I have no solutions for compiling it with this commit on Windows 7 right now because the build of armips this is using doesn't appear to be available for windows platform and cmake won't compile it on my machine.

EDIT: Seems to work fine without this change, So for now I will exlude this commit to compile future builds until this is resolved or the correct build of armips becomes available.

**Comment by mid-kid** [comment]
https://gbatemp.net/threads/release-cakesfw.391200/page-101#post-6013474
https://gbatemp.net/threads/release-cakesfw.391200/page-102#post-6014870
Both builds require microsoft visual c runtime redistributeable 2015 IIRC.
Closing as "not my problem you can't compile armips on your OS. Just use the nightlies instead or something".
(I've tried cross compiling with mingw but I gave up after a few attempts. Armips doesn't seem to like mingw. Use Visual Studio compilers instead.)

**Comment by socram8888** [comment]
For completeness sake, if you're using an old version of armips, just replace:

``` asm
.if isArm()
```

with

``` asm
.ifarm
```

and it should build
