### ISSUE TITLE
Monster Hunter 4 : An error has occured

### ISSUE THREAD

**Issue by LiKao15** [mid-kid/CakesForeveryWan#21]
I'm on o3ds / Cakes 1.08 / EmuNand 10.5 and as the titles says I can't launch my legit eshop copy of Monster Hunter 4.

As there are few reports of that error (helpful ones I mean) on the Internet I feared that my SD card was a defect or worse the 3ds itself. Just went and installed AuReiNand to be sure and the game finally booted.

No idea if Cakes 1.08 has an issue or if I'm the issue, but I thought it wouldn't hurt to tell you all this.

**Comment by mid-kid** [comment]
<img src="https://coldsophie.files.wordpress.com/2011/10/2008-to-do-list-41.jpg" width="200" height="200" />
Hint: The FAQ.
