### ISSUE TITLE
wait_key crashes console

### ISSUE THREAD

**Issue by socram8888** [mid-kid/CakesForeveryWan#22]
I've just compiled the latest version here in GitHub (9d8226478d6cf317dd3e524c099141a1c6eb0816), and my console hard-crashes (ie long press poweroff button to shutdown) when it reaches the selection menu.

I've added a few prints and it's apparently caused by the wait_key call in draw_menu, called from main to select what to do on boot. I've added one before and another after the call, and it seems it never returns.

Console is running an european 2DS with 9.2 on sysNAND, attempting to load firmware 0x50. I'm using themehax v2.2 to boot into Homebrew Channel, and then into Cakes launcher. I've tried replacing the boot.3dsx, skipping the HBC altogether, Cakes' but still crashed. Stable 108 works fine.

**Comment by mid-kid** [comment]
Try reverting the latest commit and try again?

**Comment by socram8888** [comment]
It's working fine after I reverted it.

**Comment by socram8888** [comment]
As of 778f887a492aca73aeae4bc3259c5a1cd8905a1b it's working fine again. Thanks!

**Comment by mid-kid** [comment]
:+1: (Thanks for closing, I forgot this issue)
