### ISSUE TITLE
Unable to launch the 2ds（1.21GB nand）emuNAND

### ISSUE THREAD

**Issue by wchdsk** [mid-kid/CakesForeveryWan#25]
This bugs happened in 2ds(pokemon JPN Ver) 
I found the 2ds have Two kinds of NandFlash

the one used Toshiba nand，With 988,807,168byte emuNAND backup（just like o3DS)
can launch emu

the other one used Samsung nand ,With 1,300,234,240byte emuNAND backup(just like n3DS)
cannot launch the emuNAND(not found)

I have no idea about this problem, but I think the CFW maybe read this emunand as n3DS 

forget my pool English :)

**Comment by mid-kid** [comment]
What did you use to dump your NAND?

**Comment by wchdsk** [comment]
I used GW to make and dump the emuNAND,and used D9 to get sysnand ,both 1,300,234,240byte

**Comment by mid-kid** [comment]
Use EmuNAND9 to make the emuNAND. I'm not sure what GW does to get the NAND size.

**Comment by wchdsk** [comment]
the EmuNAND9 make the same size emuNAND and also cannot launch emuNAND

**Comment by wchdsk** [comment]
when I used emunand9 to create emunand,and then used emuNAND tools to backup and restore,Now its can launch emunand thanks for help
