### ISSUE TITLE
CETK decryption fails on arm9loaderhax

### ISSUE THREAD

**Issue by ghost** [mid-kid/CakesForeveryWan#26]
On my two 3DSes, CETK/firmware.bin (Depending on if I include the firmkey) decryption fails via A9LH. They work normally via any other entrypoint.

**Comment by Syphurith** [comment]
It lacks some key needed. From A9LH it would at least miss the keys inside NATIVE_FIRM ARM9 section including Process9 NCCH. So setup the keys you have before decryption or firmlaunch.

**Comment by ghost** [comment]
Mind telling me which keys are required?

**Comment by Syphurith** [comment]
@fox8091 From [3dbrew:AES_Registers.KeySlots](https://3dbrew.org/wiki/AES_Registers#Keyslots), read the whole sheet.
I must admit I don't know what the keys should be. However if you force the console to try encrypt a known-text with its Normal Key in Keyslots, and compare the output with what you can get from other entrypoints, the comparison would tell you which keyslots are different.

**Comment by mid-kid** [comment]
For everyone getting here, just like I state on the FAQ on GBATemp, get a firmkey.bin for your console from anywhere, plailect's guide, for example: https://github.com/Plailect/Guide/wiki/Part-5-%28arm9loaderhax-&-Cakes%29
