### ISSUE TITLE
Enable log

### ISSUE THREAD

**Issue by Jhyrachy** [mid-kid/CakesForeveryWan#29]
Hi,
I'm having some problems while setting up cake because it ends with a black screen.

It would be amazing to have a checkbox to save a log so we can spot problems faster.

Thanks a lot!

**Comment by mid-kid** [comment]
That won't be necessary, as any important/breaking error pointed out by the log is put on the top screen (the log only serves to see at which point it failed). The problem probably lies in a patch which you enabled. Try booting without any patches, if that works, please tell me which patches you enabled which don't work.

**Comment by mid-kid** [comment]
Closing unless I get a response.

**Comment by Jhyrachy** [comment]
I tested a bit, it's a problem of my 3ds, since Cakes boot correctly on sysnand (with patched signature) but not in emunand and not even rxtools can boot in emunand on this 3ds

**Comment by mid-kid** [comment]
Hm, does it happen to be a 2ds with a 2GB NAND (check the size of a nand dump)?

**Comment by Jhyrachy** [comment]
No, is an Old3dsXL with a 1Gb emunand
