### ISSUE TITLE
Can't boot emuNAND 9.x from sysNAND 6.0

### ISSUE THREAD

**Issue by mid-kid** [mid-kid/CakesForeveryWan#3]
This is a weird problem, reported by Richter on IRC.
All his files are correct, updated and the md5sums and everything check out.
He appears to be loading Cakes form MSET 4.x.
His system is a 2ds.
His problem is that trying to load emuNAND 9.x is causing him a "black screen".

**Comment by Uukrull** [comment]
I just tried the latest version compiled from github and is working on my 2DS 7.2 with mset 4.x DG (both sysNAND and emuNAND). Many thanks!

**Comment by b1l1s** [comment]
You'd be interested to know that we now have mset 6.x support. Should be better for 2DSes.

Also were you the guy who reported this? Should I close this issue?

**Comment by Uukrull** [comment]
No, it wasn't me. MSET 6.x was the first option I tried but it didn't work, anyway, I ordered a CN yesterday so I'll probably upgrade my 2DS to 9.2 :)

**Comment by mid-kid** [comment]
A similar problem has been reported today on /hbg/.
The subject appears to have a 2DS on firmware 6.0.0.
His NAND size is 988 807 168 bytes.
It appears to hang on a black screen, if the emuNAND patches are selected.
Booting normally works.

Also for some reason, when booting via spider, it hangs on "Booting...", but boots if very lucky.

**Comment by Syphurith** [comment]
@mid-kid Boots if very lucky? It sounds not so stable for them or for the cakes.
_I've ever experienced similar things with rxTools. If i start my MSET too fast it may just hang with black. Personally i did wait around 10+ seconds for it to load more easily. Same for BootNTR, but that is 1min+. Could this be a timing issue for them? I still recall roxas's notes about rxTools' region patch._
Eh.. Booting normally works.. So is there any incompatible structions given in the patch?

**Comment by mid-kid** [comment]
@Syphurith Since rxTools 2.6 seems to work, I tried changing a few things in the emunand patch to have it be exactly the same as rxTools', sent it to him, and it seemed to work, once, but never again.

**Comment by Syphurith** [comment]
@mid-kid Me-ahhh.. What is "never again"? Is the patch incompatible with cakes?
I don't know when the 6.x 2DS first supported by rx, but there is "datasuite installation" for rx in 2.6+.
Note: I don't see 2DS users complain about rx now, and what they use to boot seems all similar to yours. So the patch might be the reason.

**Comment by mid-kid** [comment]
@Syphurith It seems to have booted correctly once, and the rest of the times it just hung at the same spot. (The modified patch works for me).

**Comment by Syphurith** [comment]
@mid-kid That sounds weird to me... Much sorry of not so helpful. Good luck.

**Comment by mid-kid** [comment]
Closing way too old issue that hasn't been reported by anybody else.
