### ISSUE TITLE
(question) Why CETK is needed?

### ISSUE THREAD

**Issue by mariogamer2** [mid-kid/CakesForeveryWan#35]
Other CFW don't need CETK...

**Comment by socram8888** [comment]
Other CFWs have the decrypted firmware embedded.

Cakes on the other hand decrypts it on the first run in the console, and the cetk contains they keyY needed to generate the AES key to decrypt it.

**Comment by mariogamer2** [comment]
Sorry but I don't understand the "decrypted firmware embedded"...

**Comment by mid-kid** [comment]
Other CFWs come with the decrypted firmware, cakes decrypts it on boot.
