### ISSUE TITLE
CETK not right

### ISSUE THREAD

**Issue by mariogamer2** [mid-kid/CakesForeveryWan#36]
When downloading the latest cet from [this url](https://raw.githubusercontent.com/mid-kid/CakesForeveryWan/138/firmurl) (for o3ds), It's always say me to verify if CETK is right....

Same things for an older CETK...

**Comment by mid-kid** [comment]
Are you using arm9loaderhax?

**Comment by mariogamer2** [comment]
Yeah

**Comment by mariogamer2** [comment]
Sorry I was thinking thats #26 was for N3DS (Process9).
