### ISSUE TITLE
Unable to boot emuNAND/redNAND with Cakes

### ISSUE THREAD

**Issue by gemarcano** [mid-kid/CakesForeveryWan#38]
Using commit e1a8d6b384d2caa3b27ae207d6fe03b7f73cd944. o3DS a9lh, sysNAND on 9.2, emuNAND on 10.6. Also, in case it wasn't obvious, I'm Gelex :)

The problem is that Cakes seems to be unable to boot emuNAND. I've tried most combination of patches, and even just emuNAND with nothing else. From what I can tell visibly, cakes shuts off the backlight, and it never comes back on, so whatever hangs happens before Cakes does screen re-init. Strange thing is that Cakes is able to boot sysNAND with 10.4 firm, and that works fine. I can attest that ARN can boot emuNAND fine in both GW-emuNAND and redNAND versions of the emuNAND on the SD card, while changing formats does nothing for Cakes. I re-downloaded the 10.4 firmware to make sure it wasn't corrupted, and it is fine (cmp returned no differences between a fresh download and my copy). Anything else I should check for?

**Comment by mid-kid** [comment]
It works fine for me on a 9.6 firmware, will check it out.

**Comment by mid-kid** [comment]
Unable to reproduce the problem. I've gotten a patched dump, will check out soon.

**Comment by gemarcano** [comment]
Maybe it's something about how it compiled on my machine? I can upload the patches and Cakes.dat if it helps. Although I should have everything up to date...

**Comment by mid-kid** [comment]
Please try the cakes from the official nightly. Report back. (I wouldn't be too surprised if it were the patissier.py due to alignment issues and whatnot)

**Comment by gemarcano** [comment]
Nightly works.

**Comment by mid-kid** [comment]
Please share the broken .cake. Would like to know what's wrong. With which commit was it made?

**Comment by gemarcano** [comment]
Something bizarre is going on. Here is a version that doesn't work. I also just recompiled, and it is working now. I'm going to test a few more times.

[cakes.zip](https://github.com/mid-kid/CakesForeveryWan/files/194875/cakes.zip)

**Comment by gemarcano** [comment]
Uh, Is the final size of the cake patches supposed to vary? I used 'make clean && make && du -b out/cakes/patches/*` to create these size readings.
[cake_variance.txt](https://github.com/mid-kid/CakesForeveryWan/files/194884/cake_variance.txt)

EDIT: I can confirm that some compilations work, some don't. This is really sketchy, since it looks non-deterministic to me at a glance...

**Comment by mid-kid** [comment]
The output from patissier.py is unpredictable. Python likes throwing dicts in random orders on each different run, so I can't do much about that. I've just been able to reproduce the problem, and I'll try to fix it soon. Still unsure what it may be exactly, but sometimes the generated .cake works, yet sometimes it just doesn't.

**Comment by gemarcano** [comment]
I can't reopen the issue, mid-kid, seemingly I don't have permissions to do it. But as per liomajor at  #Cakey, the bug is back.

**Comment by mid-kid** [comment]
Oh, I didn't know. Anyway, yeah, the bug is still there, but I can't seem to reproduce it again for the life of me. If someone turns up with a broken emunand.cake, please tell me, and I'll inspect it again.

**Comment by mid-kid** [comment]
Thanks to liomajor on #Cakey for help fixing this issue.
