### ISSUE TITLE
Implement thread

### ISSUE THREAD

**Issue by mariogamer2** [mid-kid/CakesForeveryWan#41]
Don't know if it is possible....

A things must be to add a cake string in setting...

**Comment by mid-kid** [comment]
No. DHS is that "thread", and 3ds_injector does the same.

**Comment by Hartie95** [comment]
It would be good for doing things like ram dumping, but its only a nice to have for some people.

**Comment by mid-kid** [comment]
DHS also does RAM dumping. But instead of running from an arm9 thread, it runs as an arm11 sysmodule (dlp). I want to port it, but not right now.
