### ISSUE TITLE
Discreet bootup?

### ISSUE THREAD

**Issue by CrispyYoshi** [mid-kid/CakesForeveryWan#44]
Hi! First of all, thanks for making such a great CFW. I noticed that auto-booting Cakes through A9LH outputs some debug text on the screen, such as loading FIRM files. Can we get an option to keep the entire bootup black? I'm hoping to make my 3DS boot up into SysNAND CFW as discreetly as possible, and am using arm9select as my initial A9LH payload.

Thanks again!

**Comment by mid-kid** [comment]
I don't care enough about it, this might take a bit. But yes, it should be easy.
