### ISSUE TITLE
I'm not able to load RedNAND

### ISSUE THREAD

**Issue by SuryaKmuar** [mid-kid/CakesForeveryWan#52]

**Comment by socram8888** [comment]
This is Cakes CFW issue tracker, not Luma3DS'

If you are having a problem with booting into EmuNAND you should ask either on https://github.com/Plailect/Guide/issues or https://github.com/AuroraWright/Luma3DS.

**Comment by SuryaKmuar** [comment]
sorry i was irritated so i posted here without knowing this is for cakes CFW issue tracker.
BTW thanks

**Comment by mid-kid** [comment]
If the issue is wrong/incorrect and you don't need any more help here, please consider closing the issue yourself next time. Thanks.
