### ISSUE TITLE
TiniVi isn't credited for screen deinit

### ISSUE THREAD

**Issue by Mrrraou** [mid-kid/CakesForeveryWan#57]
@TiniVi found out the screen deinit, but he isn't credited.

**Comment by mid-kid** [comment]
Ah, true, I did credit him in the commit, though. Will add.

**Comment by ghost** [comment]
Fixed with https://github.com/mid-kid/CakesForeveryWan/commit/4c86032a57f11ae2fffabf61424ca0145d790063
