### ISSUE TITLE
It dun wanna compile :(

### ISSUE THREAD

**Issue by ghost** [mid-kid/CakesForeveryWan#6]
My setup allows me to compile rxTools but I don't know why it doesn't work for Cakes :/

python patches/bundle.py patches/emunand/info.json patches/emunand/patches.s bui
ld/patches/emunand out/cakes/patches
ARMIPS Assembler v0.7d (Apr  1 2013 10:09:41) by Kingcom
patches.s(6) error: Invalid equation name 0x080d8670_unk2
patches.s(7) error: Invalid equation name 0x080d8670_unk1
patches.s(8) error: Invalid equation name 0x080d8670_unk0
patches.s(41) error: Invalid expression "(0x080d8670_unk0+1)"
patches.s(66) error: Invalid expression "(0x080d8670_unk1+1)"
patches.s(106) error: Invalid expression "(0x080d8670_unk0+1)"
patches.s(131) error: Invalid expression "(0x080d8670_unk2+1)"
Aborting.
Traceback (most recent call last):
  File "patches/bundle.py", line 85, in <module>
NameError: name 'ver' is not defined
make: **\* [build/patches/emunand.baked] Error 1

This is my path:

c:\devkitPro\msys\bin;C:\Program Files\ImageMagick-6.9.1-Q16;C:\devkitPro\devkitARM\bin;C:\MinGW\bin;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Overlook Fing 2.2\bin;C:\Users\Lavanoid\bin;C:\Python27;C:\Users\Lavanoid\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd; 

Help? Pretty please?

**Comment by mid-kid** [comment]
Huh, that's weird.
There's two possible problems here:
1. The python version you use is incompatible with bundle.py (Please tell me what `python --version` tells you)
2. The armips version you use fails for some reason (Not very likely, but still a possibility).

**Comment by ghost** [comment]
C:\Users\Lavanoid>python --version
Python 2.7.9

C:\Users\Lavanoid>armips
ARMIPS Assembler v0.7d (Apr  1 2013 10:09:41) by Kingcom
Usage: armips.exe file.asm [-temp temp.txt] [-sym symfile.sym]

**Comment by mid-kid** [comment]
Hm. It works fine with my python 2.7.10, and I don't think I use any incompatible api or anything in the script.
Try updating it anyway.

**Comment by ghost** [comment]
Just updated my python to 2.7.10 and it hasn't fixed anything :(

make[1]: Leaving directory `/c/Users/Lavanoid/Desktop/CakesForeveryWan/CakeHax'
dd if=build/main.bin of=out/Cakes.dat bs=512 seek=144
68+1 records in
68+1 records out
35076 bytes (35 kB) copied, 0.016 seconds, 2.2 MB/s
python patches/bundle.py patches/emunand/info.json patches/emunand/patches.s bui
ld/patches/emunand out/cakes/patches
ARMIPS Assembler v0.7d (Apr  1 2013 10:09:41) by Kingcom
patches.s(6) error: Invalid equation name 0x080d8670_unk2
patches.s(7) error: Invalid equation name 0x080d8670_unk1
patches.s(8) error: Invalid equation name 0x080d8670_unk0
patches.s(41) error: Invalid expression "(0x080d8670_unk0+1)"
patches.s(66) error: Invalid expression "(0x080d8670_unk1+1)"
patches.s(106) error: Invalid expression "(0x080d8670_unk0+1)"
patches.s(131) error: Invalid expression "(0x080d8670_unk2+1)"
Aborting.
Traceback (most recent call last):
  File "patches/bundle.py", line 85, in <module>
NameError: name 'ver' is not defined
make: **\* [build/patches/emunand.baked] Error 1

**Comment by A600** [comment]
I also have python 2.7.10 installed on my Ubuntu VM and I have the same error. I only can compile it by editing the makefile with PYTHON := python3

**Comment by ghost** [comment]
Its weird, I swear. I just compiled it on my xUbuntu VM and it worked :/

**Comment by ghost** [comment]
I guess it might help if I was using Python 3 0~0

**Comment by b1l1s** [comment]
Python 2.7.8 on windows here. Is there different releases of python in linux by any chance?

**Comment by Syphurith** [comment]
@lavanoid Python2 and Python3 differs much. Also you could get armips source and compile it, the compilition issue seems to be related to it much more than to python.
~~@b1l1s The setup included in makefile isn't really friendly. Well hope it could be solved later.~~ (wrong)

**Comment by b1l1s** [comment]
@Syphurith make a pull request :P.

I don't see why you said it's not friendly though, unless you're talking about the current python bug that we are facing.

Also @infinicore made sure that our python scripts runs in both python2 and 3. I tested his changes too.

**Comment by Syphurith** [comment]
@b1l1s Oh well i may get my local repo updated. Hope it is solved already.

**Comment by b1l1s** [comment]
@Syphurith python2 and 3 compatibility changes was made a long time ago.

I meant you should make a pull request/issue for any problem that you see in our Makefile. "Not friendly" is a bit vague, we can't possibly work from there.

**Comment by Syphurith** [comment]
@b1l1s I would try to get updated local repo compile and try to point out and solve some if have time (if there are some issues i could deal with). My previous wrong statement gets deleted ~~(just a slash)~~ now.

**Comment by b1l1s** [comment]
@Syphurith That would be great thanks. Just don't change it too much or @mid-kid (and me) will kill you :P.

**Comment by Syphurith** [comment]
@b1l1s If I have time. I would test the changes if any before it is renamed to be "merge-able".
_Been forced to prepare for papers. So only hope i am not so busy then._ All right then :P.

**Comment by Syphurith** [comment]
@b1l1s I've recalled something. @dukesrg have replaced the armips to gas for rxTools. _Maybe you could ask him for help dealing with armips for cakesfw so it could be compile-able on non-windows. And also get rid of those armips related issues._

**Comment by mid-kid** [comment]
I exclusively use Linux, and armips isn't a problem (see mid-kid/config/patches/armips-linux.patch). I see no reason for changing one syntax to the other. OP should update his armips.

**Comment by mid-kid** [comment]
At least, iirc, the latest armips build for windows on romhacking.net should work. If that isn't the case, I will try to fix that.

**Comment by ghost** [comment]
I'm using the one from romhacking.net... I can't compile armips for Windows, either >.<

**Comment by ghost** [comment]
Even with Python3, it won't work :/ Seems that cake just won't compile on Windows... That sorta sucks...

C:\Users\Lavanoid\Desktop\CakesForeveryWan>make
make[1]: Entering directory `/c/Users/Lavanoid/Desktop/CakesForeveryWan/CakeHax'

make[1]: Nothing to be done for `launcher'.
make[1]: Leaving directory`/c/Users/Lavanoid/Desktop/CakesForeveryWan/CakeHax'
dd if=build/main.bin of=out/Cakes.dat bs=512 seek=144
68+1 records in
68+1 records out
35076 bytes (35 kB) copied, 0.004 seconds, 8.8 MB/s
python patches/bundle.py patches/emunand/info.json patches/emunand/patches.s bui
ld/patches/emunand out/cakes/patches
ARMIPS Assembler v0.7d (Apr  1 2013 10:09:41) by Kingcom
patches.s(7) error: Invalid equation name 0x080d8670_unk1
patches.s(66) error: Invalid expression "(0x080d8670_unk1+1)"
Aborting.
Traceback (most recent call last):
  File "patches/bundle.py", line 85, in <module>
NameError: name 'ver' is not defined
make: **\* [build/patches/emunand.baked] Error 1

C:\Users\Lavanoid\Desktop\CakesForeveryWan>python --version
Python 3.4.3

C:\Users\Lavanoid\Desktop\CakesForeveryWan>

**Comment by mid-kid** [comment]
I think I know what's going on, but I have no idea why it happens, since @b1l1s is on windows too, and I think he also uses the romhacking.net build.
Either way, reorder the variables in patches/emunand/info.json so that sdmmc is at the end, while sdmmc_unk0 and the others are above it. Tell me if that worked.

**Comment by b1l1s** [comment]
I use my own armips build if that helps.

**Comment by ghost** [comment]
Yeah, editing the .json has helped! Now Python is being a bit of a bitch :/

make[1]: Leaving directory `/c/Users/Lavanoid/Desktop/CakesForeveryWan/CakeHax'
dd if=build/main.bin of=out/Cakes.dat bs=512 seek=144
68+1 records in
68+1 records out
35100 bytes (35 kB) copied, 0.03 seconds, 1.2 MB/s
python patches/bundle.py patches/emunand/info.json patches/emunand/patches.s bui
ld/patches/emunand out/cakes/patches
Traceback (most recent call last):
  File "patches/bundle.py", line 15, in <module>
    info = loads(open(argv[1]).read())
  File "c:\Python34\lib\json__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 32 column 5 (char 785)
make: **\* [build/patches/emunand.baked] Error 1

**Comment by mid-kid** [comment]
> Expecting ',' delimiter: line 32 column 5 (char 785)

You've forgot to put that character in some line in the json.

**Comment by ghost** [comment]
Ooops. Just fixed that, silly me. This is the new output:

C:\Users\Lavanoid\Desktop\CakesForeveryWan>make
make[1]: Entering directory `/c/Users/Lavanoid/Desktop/CakesForeveryWan/CakeHax'

make[1]: Nothing to be done for `launcher'.
make[1]: Leaving directory`/c/Users/Lavanoid/Desktop/CakesForeveryWan/CakeHax'
dd if=build/main.bin of=out/Cakes.dat bs=512 seek=144
68+1 records in
68+1 records out
35100 bytes (35 kB) copied, 0 seconds, Infinity B/s
python patches/bundle.py patches/emunand/info.json patches/emunand/patches.s bui
ld/patches/emunand out/cakes/patches
ARMIPS Assembler v0.7d (Apr  1 2013 10:09:41) by Kingcom
patches.s(6) error: Invalid equation name 0x080d8670_unk2
patches.s(7) error: Invalid equation name 0x080d8670_unk1
patches.s(8) error: Invalid equation name 0x080d8670_unk0
patches.s(41) error: Invalid expression "(0x080d8670_unk0+1)"
patches.s(66) error: Invalid expression "(0x080d8670_unk1+1)"
patches.s(106) error: Invalid expression "(0x080d8670_unk0+1)"
patches.s(131) error: Invalid expression "(0x080d8670_unk2+1)"
Aborting.
Couldn't compile version 0x49 for some reason.
make: **\* [build/patches/emunand.baked] Error 1

This is part of the json:

"version_specific": [
        {
            "console": "o3ds",
            "version": "0x49",
            "variables": {
                "sdmmc_unk0": "0x08062A28",
                "sdmmc_unk1": "0x08078970",
                "sdmmc_unk2": "0x08078750",
                "aes_setkey": "0x080575B4",
                "aes_unk": "0x0805FB48",
                "sdmmc": "0x080D8670"
            },

**Comment by ghost** [comment]
OOhh! I fixed it! :D I only moved "sdmmc" for the first part of the json, I didn't do it for the other o3ds versions.

So yeah, just move sdmmc to the bottom, for all versions and ensure python3 is used :)

**Comment by ghost** [comment]
It's being a bitch, again. Ugh, I give up. Screw Windows 0~0

python patches/bundle.py patches/emunand/info.json patches/emunand/patches.s bui
ld/patches/emunand out/cakes/patches
ARMIPS Assembler v0.7d (Apr  1 2013 10:09:41) by Kingcom
patches.s(8) error: Invalid equation name 0x080d8670_unk0
patches.s(41) error: Invalid expression "(0x080d8670_unk0+1)"
patches.s(106) error: Invalid expression "(0x080d8670_unk0+1)"
Aborting.
Couldn't compile version 0x49 for some reason.
make: **\* [build/patches/emunand.baked] Error 1

**Comment by mid-kid** [comment]
Try the latest commit.

**Comment by ghost** [comment]
That works :)

**Comment by Syphurith** [comment]
@b1l1s I've tested the newly updated repo minutes ago. And python2/3 issue was dealt quite some days ago, my apologize for having a outdated one. _That was dealt by the print and FileNotExist_. Sorry.
And for the Makefile, you may change this line in `clean` target.

``` Makefile
#Before
rm -rf $(dir_out) $(dir_build) Cakes_$(revision).zip
#After
rm -rf $(dir_out) $(dir_build) Cakes_*.zip
```

Thus previously builded zip files could also be wiped. _I'd apologize for posting this in a closed issue._
