### ISSUE TITLE
CakesFW hangs on RedNAND boot

### ISSUE THREAD

**Issue by drdeaton** [mid-kid/CakesForeveryWan#65]
When booting my redNAND, cakes hangs on a black screen after pressing "Boot CFW". THis only happens when the Enable EmuNAND patch is on. If it helps, my redNAND was created with gm9.

Btw, sorry about submitting 2 issues in 1 day.

**Comment by mid-kid** [comment]
Hm. That's weird. What entrypoint are you using? What console do you have? Could you send me a copy of your config.bin?
I'm using redNAND as well, so it's weird. I'm not sure how it's created by GM9 though.

**Comment by mid-kid** [comment]
Oh, by the way, which build are you using? Could you try 196?
