### ISSUE TITLE
Cetk not decrypting!

### ISSUE THREAD

**Issue by Resign05** [mid-kid/CakesForeveryWan#67]
Whenever I load Cakes.Firm in bootctr9 b9s 1.2 it gets the firm but can't decrypt the cetk, I don't have any of the slot files as they are no longer there. I am on 11.0-20E(cart updated) o2DS

**Comment by mid-kid** [comment]
This is a pressing issue for b9s support. There's two ways to solve this:
- Include the CETK decryption key in the program (as corbenik does, and a lot of projects seem to be doing, despite having possible copyright issues) - this is the easiest method
- Implement loading FIRM from CTRNAND and extract the key from there - While this has the added benefit of helping add the functionality of being able to load FIRM from the CTRNAND, it takes more effort, and possibly keys.

I'm leaning towards the first one.
As for an inmediate, simple, solution, I don't really have one. You could scour the internet for an appropiate firmkey.bin, or dump your firmware.bin with GodMode9.

**Comment by Resign05** [comment]
How do I actually dump the file, I looked in decrypt9 and godmode9 and found nothing

**Comment by mid-kid** [comment]
No! Sorry for incorrectly explaining. It'd give you a decrypted firmware.bin, which wouldn't need working CETK decryption to be used. Be sure to dump it from CTRNAND, not the FIRM0 or FIRM1. If you want AGB or TWL, you'd have to dump those as well.

**Comment by mid-kid** [comment]
I'm actually unsure how to dump it, but the gist of it is navigating to `titles/<upper title id>/<lower title id>` and copying the firm.bin you should find there.
Look in the firmurls file for the title ids you need.
EDIT: Nevermind, cakesfw doesn't support loading decrypted .app files. I'm unsure whether GM9 supports extracting the firm.bin from there. Please just wait a little for a proper fix.

**Comment by Resign05** [comment]
Ok thanks!

**Comment by Resign05** [comment]
Thinking about it I have had a solution, delete b9s and then open it in homebrew then reinstall b9s, do you believe that would work

**Comment by mid-kid** [comment]
I'm sorry this is taking so long. I just pushed a shitty workaround for the time being. Cakes_200.zip should be on the nightly site shortly.

**Comment by Resign05** [comment]
Thank You This Worked Perfectly!

**Comment by mid-kid** [comment]
Fixed, went with the shitty, improper solution.
