### ISSUE TITLE
TWL/AGB Broken on New3DS with v200

### ISSUE THREAD

**Issue by thetruecatboy** [mid-kid/CakesForeveryWan#68]
Launching CakesFW with the TWL/AGB firmware files on the New3DS only brings up this issue.
"Couldn't decrypt ARM9 FIRM binary
Double-Check you've got the right firmware.bin.
If you are trying to decrypt a >=9.6 firmware on a <9.6 console, please double-check your key is saved at:/slot0x11key96.bin
We remind you that you can't decrypt it on an old3DS.
If the issue persists, please file out a bug report.

FIRM that failed: TWL_FIRM (AGB_FIRM if TWL_FIRM is deleted)"
This issue is only on the New3DS. Old3DS seems to decrypt these firmware files just fine and the patches work as expected.

**Comment by mid-kid** [comment]
Huh. That is very weird. I haven't changed anything that could change this behavior.
Please verify that if you redownload the TWL_FIRM from the link in the firmurls file, and place it in /cakes/twl_firmware.bin, you can reproduce the error again. The only reason I can think of is a faulty twl_firmware.bin
Please verify the md5sum of the slot0x11key96.bin is the following: `af6dd85a583dbe1471661d2f3b90df15`.
Also, please give me the last three lines of the log on the bottom screen. Does the same happen if you try to decrypt an encrypted NATIVE_FIRM that you just downloaded?

Please note that I don't have a N3DS to test with, so this might take a bit. If you could `/query mid-kid` on freenode IRC to talk directly, that'd be appreciated.

**Comment by thetruecatboy** [comment]
Sorry for the late reply, I went to bed after I made that report.
"md5sum slot0x11key96.bin
af6dd85a583dbe1471661d2f3b90df15  slot0x11key96.bin"
The actual firmware files were dumped from my own system, then I tested the ones that I downloaded from 
https://github.com/mid-kid/CakesForeveryWan/blob/master/firmurls
Both ended up with the same results. 
"FIRM seems not encrypted
Decrypting ARM9 FIRM binary
Couldn't decrypt ARM9 FIRM binary."
I tend to not get on IRC since I am actually rather busy this week.

**Comment by mid-kid** [comment]
EDIT: Nevermind, I think I've figured it out. Try this: http://chunk.io/f/8c8528497e624341b2c503f0ac1f04c0.zip

Please only use the unmodified files in the firmurls whenever testing and/or providing bug reports, since I can't really predict what the contents of the files you extract from your console may be, or if the bug lies somewhere in however you dumped them. Unless the bug report is about using those files specifically, of course.

And I don't mind about you not being able to go on IRC. It'll get resolved eventually, but it'll just take a bit longer since I can't test on my own. Besides, it looks like our time zones do not match up at all.

**Comment by thetruecatboy** [comment]
Gets further this time, then stops at
"Decrypting ARM9 FIRM binary
Magic: 0x159467D4
Couldn't decypt ARM9 FIRM binary. "

**Comment by mid-kid** [comment]
"Further"? Could you define what you mean by that? What's different now from before? I only added a message to print out the "Magic", but if it still fails, it should still be failing where it failed before.

**Comment by thetruecatboy** [comment]
This bit 
"Magic: 0x159467D4 "
Wasn't shown in my previous error screen is what I meant by "further." I guess "It showed more this time," would be a better phrase.

**Comment by mid-kid** [comment]
Okay, could you try this, now?
http://chunk.io/f/fa7900bf9103408b938c41b23ffa73d9.zip

**Comment by thetruecatboy** [comment]
Boots up just fine now and the patches work perfectly!

**Comment by mid-kid** [comment]
That's amazing! Could you stay around while I clean up the mess I made of it and send you a few more refined versions to test? (Sorry, I won't have anything ready today, as I'm busy)

**Comment by thetruecatboy** [comment]
I can stay around and if need be, also don't hesitate to PM on the Temp. I am Lilith Valentine on the Temp.

**Comment by mid-kid** [comment]
Fixed.

**Comment by thetruecatboy** [comment]
The working patches haven't been upped to this site
http://ny1.hashbang.sh:8834/patches/
Downloading the patches from there ends up with previous issues I was having before.

**Comment by mid-kid** [comment]
The patches needed no changes to make it work - the problem was a missing key when booting with b9s, which has been rectified, as far as I know.
Have you updated to version 202?
I don't have the version I posted earlier in this thread anymore, otherwise I'd ask you to test that.

**Comment by thetruecatboy** [comment]
202 isn't posted on your nightly site. I currently don't have a working setup to compile anything from source right now.

**Comment by mid-kid** [comment]
Check [releases](https://github.com/mid-kid/CakesForeveryWan/releases) ;)

**Comment by thetruecatboy** [comment]
OwO
