### ISSUE TITLE
3ds_injector needs to be updated to work

### ISSUE THREAD

**Issue by thetruecatboy** [mid-kid/CakesForeveryWan#69]
I can't make an issue on the repo itself, but the 3ds_injector doesn't work on 11.4
https://github.com/mid-kid/3ds_injector

**Comment by mid-kid** [comment]
Where did you get the version you're using? I've updated 3ds_injector for 11.4 a long while ago.

**Comment by thetruecatboy** [comment]
I had acquired mine compiled off another site that claimed it was up to date.. So chances are mine is actually out of date.

**Comment by mid-kid** [comment]
I've updated it on http://ny1.hashbang.sh:8834/patches. Get it from there.

**Comment by thetruecatboy** [comment]
Ah! It does work! I must have grabbed and out of date file.
But did notice you forgot to up the working TWL/AGB to your nightly patches.
BTW, sorry for randomly piling a second issue on. I was meaning to make this request and forgot to do so. When you closed the last issue, I quickly remembered and made this

**Comment by mid-kid** [comment]
Nah, if you look at the date of the last commit in lgy_cakes, they haven't been updated in ages. I'm pretty sure they're the latest.
