### ISSUE TITLE
I have decided to continue on CakesFW, and I was building the source code (yes, I have an environment set up), but

### ISSUE THREAD

**Issue by Multimegamander** [mid-kid/CakesForeveryWan#71]
I get this error:

convert source/font.pbm source/font.mono
Invalid Parameter - /font.pbm
make: *** [Makefile:136: source/font.mono] Error 4

**Comment by mid-kid** [comment]
Sorry for the late response.
Try this patch:
```diff
diff --git a/Makefile b/Makefile
index 0f11a97..5eb6e83 100644
--- a/Makefile
+++ b/Makefile
@@ -131,8 +131,8 @@ $(dir_build)/%.o: $(dir_source)/%.mono
        @mkdir -p "$(@D)"
        printf '.global $*\n$*: .incbin "$<"\n' | $(COMPILE.s) $(OUTPUT_OPTION)
 
-$(dir_source)/%.mono: $(dir_source)/%.pbm
+$(dir_source)/%.mono: | $(dir_source)/%.pbm
        @mkdir -p "$(@D)"
-       $(CONVERT) $< $@
+       $(CONVERT) $| $@
 
 include $(call rwildcard, $(dir_build), *.d)
```

This file is supposed to be generated by imagemagick's `convert` tool, which it doesn't seem you have, but it should work without said tool as well, as it's only used for a single font, nothing else, and said compiled font is distributed in the repo.

If this works, create a fixing commit. If you're willing to continue CakesFW, we're probably going to need some communication channel so I can guide you through the code. Do you use IRC, Discord, Telegram or anything else?

**Comment by Multimegamander** [comment]
I'm on Discord for 18 hours a day :3        Multimegamander#6980

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>diff --git a/Makefile b/Makefile
diff: unknown option -- git
diff: Try 'diff --help' for more information.

C:\Windows\system32>index 0f11a97..5eb6e83 100644
'index' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>--- a/Makefile
'---' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>+++ b/Makefile
'+++' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>@@ -131,8 +131,8 @@ $(dir_build)/%.o: $(dir_source)/%.mono
'-131' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>        @mkdir -p "$(@D)"
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file $(@D) already exists.
Error occurred while processing: $(@D).

C:\Windows\system32>        printf '.global $*\n$*: .incbin "$<"\n' | $(COMPILE.
s) $(OUTPUT_OPTION)
'$' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>
C:\Windows\system32>-$(dir_source)/%.mono: $(dir_source)/%.pbm
'-$' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>+$(dir_source)/%.mono: | $(dir_source)/%.pbm
'+$' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>        @mkdir -p "$(@D)"
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file $(@D) already exists.
Error occurred while processing: $(@D).

C:\Windows\system32>-       $(CONVERT) $< $@
The system cannot find the file specified.

C:\Windows\system32>+       $(CONVERT) $| $@
'+' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>
C:\Windows\system32> include $(call rwildcard, $(dir_build), *.d)
'include' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chaoskagami** [comment]
Uh...you apply that with the unix command `patch` and not cmd.exe. It's not a batch file.

You need to install something like cygwin or msys2. I'm pretty sure devkitpro's installer provides one of those, doesn't it?

Are you sure you know enough to continue development of Cakes? @mid-kid, this post has me rather concerned. :/

**Comment by Multimegamander** [comment]
I know how to code, just umm..... I never took the time to understand compiling, :/, but I do have msys2 and cygwin64 installed

**Comment by Multimegamander** [comment]
I always asked someone else to compile the code for me

**Comment by Multimegamander** [comment]
Nop, same error in Msys and Cygwin :|

**Comment by mid-kid** [comment]
https://github.com/mid-kid/CakesForeveryWan/commit/6a4d549a88002ae872ea2ae13e390f37db1bf033 hopefully solves this issue.
